ABOUT_TEXT = """
Image Watcher v1.0
----------------------------------------
Image Watcher is a simple tool designed to help you quickly view, sort, and manage images in a directory.
It is especially useful for managing large sets of images generated by AI tools, such as Stable Diffusion.

Key Features:
----------------------------------------
• Live Updates: Automatically detects new images added to the watched folder.
• Image Navigation: Easily browse through images using the navigation buttons or keyboard shortcuts (Left/Right arrow keys).
• Image Deletion: Quickly delete unwanted images with a simple click or the 'Del' key.
• Image Saving: Move images to a designated 'Saved Images' folder for later use with a click or the 'Ins' key.
• Quick Actions: Toggle quick move and delete options to bypass confirmation dialogs.
• Image Statistics: Displays image metadata such as file size, dimensions, and modification date.
• PNG Metadata: Extracts and displays PNG metadata, including Stable Diffusion parameters.
• Filtering: Filter images based on various parameters extracted from PNG metadata.
• Customization: Toggle command row, stats display, and always-on-top mode.
• Context Menu: Right-click on the image to access common actions.
• Dragging: Click and drag the image to move the window.

Usage Tips:
----------------------------------------
• Use the file menu to change the watched folder or refresh the image index.
• Enable live mode to automatically update the image list when new images are added.
• Use the filter entry to search for images based on specific criteria.
• Customize the interface using the view menu.
• Use the quick switch button to quickly return to the first image in the list.

Keyboard Shortcuts:
----------------------------------------
• Left/Right Arrow Keys: Navigate through images.
• Del: Delete the current image.
• Ins: Move the current image to the saved folder.

Notes:
----------------------------------------
• The 'Saved Images' folder is created automatically in the watched folder.
• The image database is stored in a JSON file in the watched folder.
"""


FILTER_HELP_TEXT = """
- Use the 'Search' menu and select a filter type(s).
- Enter keywords based on the selected type(s).
- Press 'Enter' to apply the filter.
- Use the 'Clear' button to reset filters.
- Use the 'Refresh' button to update the database.
- Live Mode is disabled when filters are active.
----------------------------------------
- Operators:
----------------------------------------
• Spaces are treated as AND operators.

• Prefix with '-' to exclude that term 'NOT':
    sunset -beach
Match with "sunset" but NOT "beach"

• Use '~' to match either term 'OR':
    mountain ~ lake
Show either "mountain" OR "lake".

• Use quotes to match exact phrases:
    "mountain lake"
Match "mountain lake" as a single term.

• Use a Mix of AND, OR, NOT, and Parentheses:
1)  "mountain ~ lake" sunset -beach
Show "mountain" OR "lake" at sunset but NOT "beach".

2)  -"mountain ~ lake" sunset beach
NOT images of "mountain" OR "lake" at sunset AND beach.
"""
